import type { Config } from "tailwindcss";
import scrollbar from "tailwind-scrollbar";

export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--neutral-2)",
        foreground: "var(--neutral-11)",
        brand: {
          blue: "#41aec4",
          purple: "#1d224b",
          black: "#000000",
        },
        primary: {
          DEFAULT: "var(--primary-9)",
          foreground: "var(--primary-foreground)",
          1: "var(--primary-1)",
          2: "var(--primary-2)",
          3: "var(--primary-3)",
          4: "var(--primary-4)",
          5: "var(--primary-5)",
          6: "var(--primary-6)",
          7: "var(--primary-7)",
          8: "var(--primary-8)",
          9: "var(--primary-9)",
          10: "var(--primary-10)",
          11: "var(--primary-11)",
          12: "var(--primary-12)",
        },
        neutral: {
          1: "var(--neutral-1)",
          2: "var(--neutral-2)",
          3: "var(--neutral-3)",
          4: "var(--neutral-4)",
          5: "var(--neutral-5)",
          6: "var(--neutral-6)",
          7: "var(--neutral-7)",
          8: "var(--neutral-8)",
          9: "var(--neutral-9)",
          10: "var(--neutral-10)",
          11: "var(--neutral-11)",
          12: "var(--neutral-12)",
        },
        error: {
          1: "var(--error-1)",
          2: "var(--error-2)",
          3: "var(--error-3)",
          4: "var(--error-4)",
          5: "var(--error-5)",
          6: "var(--error-6)",
          7: "var(--error-7)",
          8: "var(--error-8)",
          9: "var(--error-9)",
          10: "var(--error-10)",
          11: "var(--error-11)",
          12: "var(--error-12)",
        },
        warning: {
          1: "var(--warning-1)",
          2: "var(--warning-2)",
          3: "var(--warning-3)",
          4: "var(--warning-4)",
          5: "var(--warning-5)",
          6: "var(--warning-6)",
          7: "var(--warning-7)",
          8: "var(--warning-8)",
          9: "var(--warning-9)",
          10: "var(--warning-10)",
          11: "var(--warning-11)",
          12: "var(--warning-12)",
        },
        link: {
          1: "var(--link-1)",
          2: "var(--link-2)",
          3: "var(--link-3)",
          4: "var(--link-4)",
          5: "var(--link-5)",
          6: "var(--link-6)",
          7: "var(--link-7)",
          8: "var(--link-8)",
          9: "var(--link-9)",
          10: "var(--link-10)",
          11: "var(--link-11)",
          12: "var(--link-12)",
        },
        green: {
          1: "var(--green-1)",
          2: "var(--green-2)",
          3: "var(--green-3)",
          4: "var(--green-4)",
          5: "var(--green-5)",
          6: "var(--green-6)",
          7: "var(--green-7)",
          8: "var(--green-8)",
          9: "var(--green-9)",
          10: "var(--green-10)",
          11: "var(--green-11)",
          12: "var(--green-12)",
        },
        purple: {
          1: "var(--purple-1)",
          2: "var(--purple-2)",
          3: "var(--purple-3)",
          4: "var(--purple-4)",
          5: "var(--purple-5)",
          6: "var(--purple-6)",
          7: "var(--purple-7)",
          8: "var(--purple-8)",
          9: "var(--purple-9)",
          10: "var(--purple-10)",
          11: "var(--purple-11)",
          12: "var(--purple-12)",
        },
      },
      fontFamily: {
        sora: ["var(--font-sora)", "sans-serif"],
        "be-vietnam-pro": ["var(--font-be-vietnam-pro)", "sans-serif"],
      },
      animation: {
        ripple:
          "ripple var(--duration, 3s) ease calc(var(--i, 0) * 0.2s) infinite",
        shine: "shine var(--duration, 14s) infinite linear",
      },
      keyframes: {
        ripple: {
          "0%, 100%": {
            transform: "translate(-50%, -50%) scale(1)",
          },
          "50%": {
            transform: "translate(-50%, -50%) scale(0.9)",
          },
        },
        shine: {
          "0%": {
            backgroundPosition: "0% 0%",
          },
          "50%": {
            backgroundPosition: "100% 100%",
          },
          "100%": {
            backgroundPosition: "0% 0%",
          },
        },
      },
    },
  },
  plugins: [scrollbar({ nocompatible: true })],
} satisfies Config;
