/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AdrAbiInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "burnNFTByOperator"
      | "burnTokens"
      | "emergencyPaused"
      | "mintNFT"
      | "nftContract"
      | "operators"
      | "paymentToken"
      | "purchaseAndMintNFT"
      | "setEmergencyPause"
      | "setNFTContract"
      | "setPaymentToken"
      | "updateOperator"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyPauseSet"
      | "NFTBurned"
      | "NFTMinted"
      | "OperatorUpdated"
      | "TokensBurned"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "burnNFTByOperator",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "burnTokens",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintNFT",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "nftContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "operators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseAndMintNFT",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setEmergencyPause",
    values: [boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setNFTContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPaymentToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOperator",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "burnNFTByOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burnTokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nftContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operators", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseAndMintNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEmergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNFTContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPaymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOperator",
    data: BytesLike
  ): Result;
}

export namespace EmergencyPauseSetEvent {
  export type InputTuple = [paused: boolean, reason: string];
  export type OutputTuple = [paused: boolean, reason: string];
  export interface OutputObject {
    paused: boolean;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTBurnedEvent {
  export type InputTuple = [tokenId: BigNumberish];
  export type OutputTuple = [tokenId: bigint];
  export interface OutputObject {
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTMintedEvent {
  export type InputTuple = [
    recipient: AddressLike,
    tokenId: BigNumberish,
    uri: string
  ];
  export type OutputTuple = [recipient: string, tokenId: bigint, uri: string];
  export interface OutputObject {
    recipient: string;
    tokenId: bigint;
    uri: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorUpdatedEvent {
  export type InputTuple = [operator: AddressLike, isAdded: boolean];
  export type OutputTuple = [operator: string, isAdded: boolean];
  export interface OutputObject {
    operator: string;
    isAdded: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensBurnedEvent {
  export type InputTuple = [
    payer: AddressLike,
    amount: BigNumberish,
    description: string
  ];
  export type OutputTuple = [
    payer: string,
    amount: bigint,
    description: string
  ];
  export interface OutputObject {
    payer: string;
    amount: bigint;
    description: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AdrAbi extends BaseContract {
  connect(runner?: ContractRunner | null): AdrAbi;
  waitForDeployment(): Promise<this>;

  interface: AdrAbiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  burnNFTByOperator: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  burnTokens: TypedContractMethod<
    [amount: BigNumberish, description: string],
    [void],
    "nonpayable"
  >;

  emergencyPaused: TypedContractMethod<[], [boolean], "view">;

  mintNFT: TypedContractMethod<
    [to: AddressLike, uri: string],
    [bigint],
    "nonpayable"
  >;

  nftContract: TypedContractMethod<[], [string], "view">;

  operators: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  paymentToken: TypedContractMethod<[], [string], "view">;

  purchaseAndMintNFT: TypedContractMethod<
    [uri: string, price: BigNumberish, description: string],
    [bigint],
    "nonpayable"
  >;

  setEmergencyPause: TypedContractMethod<
    [paused: boolean, reason: string],
    [void],
    "nonpayable"
  >;

  setNFTContract: TypedContractMethod<
    [_nftContract: AddressLike],
    [void],
    "nonpayable"
  >;

  setPaymentToken: TypedContractMethod<
    [_paymentToken: AddressLike],
    [void],
    "nonpayable"
  >;

  updateOperator: TypedContractMethod<
    [operator: AddressLike, isAdded: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "burnNFTByOperator"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "burnTokens"
  ): TypedContractMethod<
    [amount: BigNumberish, description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "mintNFT"
  ): TypedContractMethod<
    [to: AddressLike, uri: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nftContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "operators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseAndMintNFT"
  ): TypedContractMethod<
    [uri: string, price: BigNumberish, description: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setEmergencyPause"
  ): TypedContractMethod<
    [paused: boolean, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setNFTContract"
  ): TypedContractMethod<[_nftContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaymentToken"
  ): TypedContractMethod<[_paymentToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateOperator"
  ): TypedContractMethod<
    [operator: AddressLike, isAdded: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EmergencyPauseSet"
  ): TypedContractEvent<
    EmergencyPauseSetEvent.InputTuple,
    EmergencyPauseSetEvent.OutputTuple,
    EmergencyPauseSetEvent.OutputObject
  >;
  getEvent(
    key: "NFTBurned"
  ): TypedContractEvent<
    NFTBurnedEvent.InputTuple,
    NFTBurnedEvent.OutputTuple,
    NFTBurnedEvent.OutputObject
  >;
  getEvent(
    key: "NFTMinted"
  ): TypedContractEvent<
    NFTMintedEvent.InputTuple,
    NFTMintedEvent.OutputTuple,
    NFTMintedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorUpdated"
  ): TypedContractEvent<
    OperatorUpdatedEvent.InputTuple,
    OperatorUpdatedEvent.OutputTuple,
    OperatorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokensBurned"
  ): TypedContractEvent<
    TokensBurnedEvent.InputTuple,
    TokensBurnedEvent.OutputTuple,
    TokensBurnedEvent.OutputObject
  >;

  filters: {
    "EmergencyPauseSet(bool,string)": TypedContractEvent<
      EmergencyPauseSetEvent.InputTuple,
      EmergencyPauseSetEvent.OutputTuple,
      EmergencyPauseSetEvent.OutputObject
    >;
    EmergencyPauseSet: TypedContractEvent<
      EmergencyPauseSetEvent.InputTuple,
      EmergencyPauseSetEvent.OutputTuple,
      EmergencyPauseSetEvent.OutputObject
    >;

    "NFTBurned(uint256)": TypedContractEvent<
      NFTBurnedEvent.InputTuple,
      NFTBurnedEvent.OutputTuple,
      NFTBurnedEvent.OutputObject
    >;
    NFTBurned: TypedContractEvent<
      NFTBurnedEvent.InputTuple,
      NFTBurnedEvent.OutputTuple,
      NFTBurnedEvent.OutputObject
    >;

    "NFTMinted(address,uint256,string)": TypedContractEvent<
      NFTMintedEvent.InputTuple,
      NFTMintedEvent.OutputTuple,
      NFTMintedEvent.OutputObject
    >;
    NFTMinted: TypedContractEvent<
      NFTMintedEvent.InputTuple,
      NFTMintedEvent.OutputTuple,
      NFTMintedEvent.OutputObject
    >;

    "OperatorUpdated(address,bool)": TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;
    OperatorUpdated: TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;

    "TokensBurned(address,uint256,string)": TypedContractEvent<
      TokensBurnedEvent.InputTuple,
      TokensBurnedEvent.OutputTuple,
      TokensBurnedEvent.OutputObject
    >;
    TokensBurned: TypedContractEvent<
      TokensBurnedEvent.InputTuple,
      TokensBurnedEvent.OutputTuple,
      TokensBurnedEvent.OutputObject
    >;
  };
}
