/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ControllerAbiInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "MIN_BURN_INTERVAL"
      | "OPERATOR_ROLE"
      | "PAUSER_ROLE"
      | "TIMELOCK_DELAY"
      | "USER_DAILY_BURN_LIMIT"
      | "burn"
      | "burnNFT"
      | "cancelScheduledAction"
      | "dailyBurnAmount"
      | "dailyBurnLimit"
      | "dailyMintCount"
      | "dailyMintLimit"
      | "emergencyPause"
      | "emergencyUnpause"
      | "executeNFTContract"
      | "executePaymentToken"
      | "executeSigner"
      | "getDailyBurnUsage"
      | "getDailyMintUsage"
      | "getNextAllowedBurnTime"
      | "getRemainingDailyBurnLimit"
      | "getRemainingUserDailyBurnLimit"
      | "getRoleAdmin"
      | "getUserDailyBurnUsage"
      | "grantRole"
      | "hasRole"
      | "lastBurnTime"
      | "mint"
      | "nftContract"
      | "paused"
      | "paymentToken"
      | "pendingChanges"
      | "renounceRole"
      | "revokeRole"
      | "scheduleNFTContract"
      | "schedulePaymentToken"
      | "scheduleSigner"
      | "setDailyLimits"
      | "setUserDailyBurnLimit"
      | "signer"
      | "supportsInterface"
      | "updateOperator"
      | "usedMessageHashes"
      | "userDailyBurnAmount"
      | "userDailyBurns"
      | "verifySignature"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminActionCancelled"
      | "AdminActionExecuted"
      | "AdminActionScheduled"
      | "DailyLimitsUpdated"
      | "NFTBurned"
      | "NFTContractUpdated"
      | "NFTMinted"
      | "Paused"
      | "PaymentTokenUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SecurityIncident"
      | "SignerUpdated"
      | "TokensBurned"
      | "Unpaused"
      | "UserDailyLimitUpdated"
      | "VerifiedTokensBurned"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_BURN_INTERVAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAUSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIMELOCK_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USER_DAILY_BURN_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "burn",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "burnNFT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelScheduledAction",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyBurnAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyBurnLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dailyMintCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyMintLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyUnpause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeNFTContract",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executePaymentToken",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSigner",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDailyBurnUsage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDailyMintUsage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNextAllowedBurnTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingDailyBurnLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingUserDailyBurnLimit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserDailyBurnUsage",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastBurnTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "nftContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingChanges",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleNFTContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "schedulePaymentToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDailyLimits",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserDailyBurnLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "signer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOperator",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "usedMessageHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userDailyBurnAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userDailyBurns",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySignature",
    values: [AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_BURN_INTERVAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAUSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIMELOCK_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USER_DAILY_BURN_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burnNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelScheduledAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyBurnAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyBurnLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyMintCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyMintLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyUnpause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeNFTContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executePaymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDailyBurnUsage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDailyMintUsage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextAllowedBurnTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingDailyBurnLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingUserDailyBurnLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserDailyBurnUsage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastBurnTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nftContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingChanges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "scheduleNFTContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "schedulePaymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDailyLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserDailyBurnLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedMessageHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userDailyBurnAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userDailyBurns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySignature",
    data: BytesLike
  ): Result;
}

export namespace AdminActionCancelledEvent {
  export type InputTuple = [
    actionId: BytesLike,
    actionType: string,
    canceller: AddressLike
  ];
  export type OutputTuple = [
    actionId: string,
    actionType: string,
    canceller: string
  ];
  export interface OutputObject {
    actionId: string;
    actionType: string;
    canceller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminActionExecutedEvent {
  export type InputTuple = [
    actionId: BytesLike,
    actionType: string,
    executor: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    actionId: string,
    actionType: string,
    executor: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    actionId: string;
    actionType: string;
    executor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminActionScheduledEvent {
  export type InputTuple = [
    actionId: BytesLike,
    actionType: string,
    initiator: AddressLike,
    executeTime: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [
    actionId: string,
    actionType: string,
    initiator: string,
    executeTime: bigint,
    data: string
  ];
  export interface OutputObject {
    actionId: string;
    actionType: string;
    initiator: string;
    executeTime: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DailyLimitsUpdatedEvent {
  export type InputTuple = [
    newBurnLimit: BigNumberish,
    newMintLimit: BigNumberish
  ];
  export type OutputTuple = [newBurnLimit: bigint, newMintLimit: bigint];
  export interface OutputObject {
    newBurnLimit: bigint;
    newMintLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTBurnedEvent {
  export type InputTuple = [tokenId: BigNumberish, operator: AddressLike];
  export type OutputTuple = [tokenId: bigint, operator: string];
  export interface OutputObject {
    tokenId: bigint;
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTContractUpdatedEvent {
  export type InputTuple = [oldNFT: AddressLike, newNFT: AddressLike];
  export type OutputTuple = [oldNFT: string, newNFT: string];
  export interface OutputObject {
    oldNFT: string;
    newNFT: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTMintedEvent {
  export type InputTuple = [
    recipient: AddressLike,
    tokenId: BigNumberish,
    uri: string,
    operator: AddressLike
  ];
  export type OutputTuple = [
    recipient: string,
    tokenId: bigint,
    uri: string,
    operator: string
  ];
  export interface OutputObject {
    recipient: string;
    tokenId: bigint;
    uri: string;
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentTokenUpdatedEvent {
  export type InputTuple = [oldToken: AddressLike, newToken: AddressLike];
  export type OutputTuple = [oldToken: string, newToken: string];
  export interface OutputObject {
    oldToken: string;
    newToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecurityIncidentEvent {
  export type InputTuple = [
    user: AddressLike,
    incidentType: string,
    amount: BigNumberish,
    timestamp: BigNumberish,
    details: string
  ];
  export type OutputTuple = [
    user: string,
    incidentType: string,
    amount: bigint,
    timestamp: bigint,
    details: string
  ];
  export interface OutputObject {
    user: string;
    incidentType: string;
    amount: bigint;
    timestamp: bigint;
    details: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerUpdatedEvent {
  export type InputTuple = [oldSigner: AddressLike, newSigner: AddressLike];
  export type OutputTuple = [oldSigner: string, newSigner: string];
  export interface OutputObject {
    oldSigner: string;
    newSigner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensBurnedEvent {
  export type InputTuple = [
    payer: AddressLike,
    amount: BigNumberish,
    description: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    payer: string,
    amount: bigint,
    description: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    payer: string;
    amount: bigint;
    description: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserDailyLimitUpdatedEvent {
  export type InputTuple = [newLimit: BigNumberish];
  export type OutputTuple = [newLimit: bigint];
  export interface OutputObject {
    newLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifiedTokensBurnedEvent {
  export type InputTuple = [
    payer: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish,
    messageHash: BytesLike
  ];
  export type OutputTuple = [
    payer: string,
    amount: bigint,
    timestamp: bigint,
    messageHash: string
  ];
  export interface OutputObject {
    payer: string;
    amount: bigint;
    timestamp: bigint;
    messageHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ControllerAbi extends BaseContract {
  connect(runner?: ContractRunner | null): ControllerAbi;
  waitForDeployment(): Promise<this>;

  interface: ControllerAbiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MIN_BURN_INTERVAL: TypedContractMethod<[], [bigint], "view">;

  OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  PAUSER_ROLE: TypedContractMethod<[], [string], "view">;

  TIMELOCK_DELAY: TypedContractMethod<[], [bigint], "view">;

  USER_DAILY_BURN_LIMIT: TypedContractMethod<[], [bigint], "view">;

  burn: TypedContractMethod<
    [amount: BigNumberish, timestamp: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  burnNFT: TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;

  cancelScheduledAction: TypedContractMethod<
    [actionId: BytesLike, actionType: string],
    [void],
    "nonpayable"
  >;

  dailyBurnAmount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  dailyBurnLimit: TypedContractMethod<[], [bigint], "view">;

  dailyMintCount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  dailyMintLimit: TypedContractMethod<[], [bigint], "view">;

  emergencyPause: TypedContractMethod<[], [void], "nonpayable">;

  emergencyUnpause: TypedContractMethod<[], [void], "nonpayable">;

  executeNFTContract: TypedContractMethod<
    [actionId: BytesLike],
    [void],
    "nonpayable"
  >;

  executePaymentToken: TypedContractMethod<
    [actionId: BytesLike],
    [void],
    "nonpayable"
  >;

  executeSigner: TypedContractMethod<
    [actionId: BytesLike],
    [void],
    "nonpayable"
  >;

  getDailyBurnUsage: TypedContractMethod<[day: BigNumberish], [bigint], "view">;

  getDailyMintUsage: TypedContractMethod<[day: BigNumberish], [bigint], "view">;

  getNextAllowedBurnTime: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getRemainingDailyBurnLimit: TypedContractMethod<[], [bigint], "view">;

  getRemainingUserDailyBurnLimit: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getUserDailyBurnUsage: TypedContractMethod<
    [user: AddressLike, day: BigNumberish],
    [bigint],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  lastBurnTime: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  mint: TypedContractMethod<
    [to: AddressLike, uri: string],
    [bigint],
    "nonpayable"
  >;

  nftContract: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  paymentToken: TypedContractMethod<[], [string], "view">;

  pendingChanges: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, boolean, string] & {
        executeTime: bigint;
        executed: boolean;
        data: string;
      }
    ],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  scheduleNFTContract: TypedContractMethod<
    [_newNFT: AddressLike],
    [void],
    "nonpayable"
  >;

  schedulePaymentToken: TypedContractMethod<
    [_newToken: AddressLike],
    [void],
    "nonpayable"
  >;

  scheduleSigner: TypedContractMethod<
    [_newSigner: AddressLike],
    [void],
    "nonpayable"
  >;

  setDailyLimits: TypedContractMethod<
    [_burnLimit: BigNumberish, _mintLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  setUserDailyBurnLimit: TypedContractMethod<
    [_limit: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  updateOperator: TypedContractMethod<
    [operator: AddressLike, isAdded: boolean],
    [void],
    "nonpayable"
  >;

  usedMessageHashes: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  userDailyBurnAmount: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  userDailyBurns: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  verifySignature: TypedContractMethod<
    [
      wallet: AddressLike,
      amount: BigNumberish,
      timestamp: BigNumberish,
      signature: BytesLike
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MIN_BURN_INTERVAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PAUSER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TIMELOCK_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USER_DAILY_BURN_LIMIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<
    [amount: BigNumberish, timestamp: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "burnNFT"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelScheduledAction"
  ): TypedContractMethod<
    [actionId: BytesLike, actionType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dailyBurnAmount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyBurnLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyMintCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyMintLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyPause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyUnpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeNFTContract"
  ): TypedContractMethod<[actionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executePaymentToken"
  ): TypedContractMethod<[actionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeSigner"
  ): TypedContractMethod<[actionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDailyBurnUsage"
  ): TypedContractMethod<[day: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDailyMintUsage"
  ): TypedContractMethod<[day: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNextAllowedBurnTime"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRemainingDailyBurnLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRemainingUserDailyBurnLimit"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUserDailyBurnUsage"
  ): TypedContractMethod<
    [user: AddressLike, day: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastBurnTime"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [to: AddressLike, uri: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nftContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingChanges"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, boolean, string] & {
        executeTime: bigint;
        executed: boolean;
        data: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scheduleNFTContract"
  ): TypedContractMethod<[_newNFT: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "schedulePaymentToken"
  ): TypedContractMethod<[_newToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scheduleSigner"
  ): TypedContractMethod<[_newSigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDailyLimits"
  ): TypedContractMethod<
    [_burnLimit: BigNumberish, _mintLimit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setUserDailyBurnLimit"
  ): TypedContractMethod<[_limit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateOperator"
  ): TypedContractMethod<
    [operator: AddressLike, isAdded: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usedMessageHashes"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "userDailyBurnAmount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userDailyBurns"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifySignature"
  ): TypedContractMethod<
    [
      wallet: AddressLike,
      amount: BigNumberish,
      timestamp: BigNumberish,
      signature: BytesLike
    ],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AdminActionCancelled"
  ): TypedContractEvent<
    AdminActionCancelledEvent.InputTuple,
    AdminActionCancelledEvent.OutputTuple,
    AdminActionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "AdminActionExecuted"
  ): TypedContractEvent<
    AdminActionExecutedEvent.InputTuple,
    AdminActionExecutedEvent.OutputTuple,
    AdminActionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "AdminActionScheduled"
  ): TypedContractEvent<
    AdminActionScheduledEvent.InputTuple,
    AdminActionScheduledEvent.OutputTuple,
    AdminActionScheduledEvent.OutputObject
  >;
  getEvent(
    key: "DailyLimitsUpdated"
  ): TypedContractEvent<
    DailyLimitsUpdatedEvent.InputTuple,
    DailyLimitsUpdatedEvent.OutputTuple,
    DailyLimitsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NFTBurned"
  ): TypedContractEvent<
    NFTBurnedEvent.InputTuple,
    NFTBurnedEvent.OutputTuple,
    NFTBurnedEvent.OutputObject
  >;
  getEvent(
    key: "NFTContractUpdated"
  ): TypedContractEvent<
    NFTContractUpdatedEvent.InputTuple,
    NFTContractUpdatedEvent.OutputTuple,
    NFTContractUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NFTMinted"
  ): TypedContractEvent<
    NFTMintedEvent.InputTuple,
    NFTMintedEvent.OutputTuple,
    NFTMintedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentTokenUpdated"
  ): TypedContractEvent<
    PaymentTokenUpdatedEvent.InputTuple,
    PaymentTokenUpdatedEvent.OutputTuple,
    PaymentTokenUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SecurityIncident"
  ): TypedContractEvent<
    SecurityIncidentEvent.InputTuple,
    SecurityIncidentEvent.OutputTuple,
    SecurityIncidentEvent.OutputObject
  >;
  getEvent(
    key: "SignerUpdated"
  ): TypedContractEvent<
    SignerUpdatedEvent.InputTuple,
    SignerUpdatedEvent.OutputTuple,
    SignerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokensBurned"
  ): TypedContractEvent<
    TokensBurnedEvent.InputTuple,
    TokensBurnedEvent.OutputTuple,
    TokensBurnedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "UserDailyLimitUpdated"
  ): TypedContractEvent<
    UserDailyLimitUpdatedEvent.InputTuple,
    UserDailyLimitUpdatedEvent.OutputTuple,
    UserDailyLimitUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VerifiedTokensBurned"
  ): TypedContractEvent<
    VerifiedTokensBurnedEvent.InputTuple,
    VerifiedTokensBurnedEvent.OutputTuple,
    VerifiedTokensBurnedEvent.OutputObject
  >;

  filters: {
    "AdminActionCancelled(bytes32,string,address)": TypedContractEvent<
      AdminActionCancelledEvent.InputTuple,
      AdminActionCancelledEvent.OutputTuple,
      AdminActionCancelledEvent.OutputObject
    >;
    AdminActionCancelled: TypedContractEvent<
      AdminActionCancelledEvent.InputTuple,
      AdminActionCancelledEvent.OutputTuple,
      AdminActionCancelledEvent.OutputObject
    >;

    "AdminActionExecuted(bytes32,string,address,uint256)": TypedContractEvent<
      AdminActionExecutedEvent.InputTuple,
      AdminActionExecutedEvent.OutputTuple,
      AdminActionExecutedEvent.OutputObject
    >;
    AdminActionExecuted: TypedContractEvent<
      AdminActionExecutedEvent.InputTuple,
      AdminActionExecutedEvent.OutputTuple,
      AdminActionExecutedEvent.OutputObject
    >;

    "AdminActionScheduled(bytes32,string,address,uint256,bytes)": TypedContractEvent<
      AdminActionScheduledEvent.InputTuple,
      AdminActionScheduledEvent.OutputTuple,
      AdminActionScheduledEvent.OutputObject
    >;
    AdminActionScheduled: TypedContractEvent<
      AdminActionScheduledEvent.InputTuple,
      AdminActionScheduledEvent.OutputTuple,
      AdminActionScheduledEvent.OutputObject
    >;

    "DailyLimitsUpdated(uint256,uint256)": TypedContractEvent<
      DailyLimitsUpdatedEvent.InputTuple,
      DailyLimitsUpdatedEvent.OutputTuple,
      DailyLimitsUpdatedEvent.OutputObject
    >;
    DailyLimitsUpdated: TypedContractEvent<
      DailyLimitsUpdatedEvent.InputTuple,
      DailyLimitsUpdatedEvent.OutputTuple,
      DailyLimitsUpdatedEvent.OutputObject
    >;

    "NFTBurned(uint256,address)": TypedContractEvent<
      NFTBurnedEvent.InputTuple,
      NFTBurnedEvent.OutputTuple,
      NFTBurnedEvent.OutputObject
    >;
    NFTBurned: TypedContractEvent<
      NFTBurnedEvent.InputTuple,
      NFTBurnedEvent.OutputTuple,
      NFTBurnedEvent.OutputObject
    >;

    "NFTContractUpdated(address,address)": TypedContractEvent<
      NFTContractUpdatedEvent.InputTuple,
      NFTContractUpdatedEvent.OutputTuple,
      NFTContractUpdatedEvent.OutputObject
    >;
    NFTContractUpdated: TypedContractEvent<
      NFTContractUpdatedEvent.InputTuple,
      NFTContractUpdatedEvent.OutputTuple,
      NFTContractUpdatedEvent.OutputObject
    >;

    "NFTMinted(address,uint256,string,address)": TypedContractEvent<
      NFTMintedEvent.InputTuple,
      NFTMintedEvent.OutputTuple,
      NFTMintedEvent.OutputObject
    >;
    NFTMinted: TypedContractEvent<
      NFTMintedEvent.InputTuple,
      NFTMintedEvent.OutputTuple,
      NFTMintedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PaymentTokenUpdated(address,address)": TypedContractEvent<
      PaymentTokenUpdatedEvent.InputTuple,
      PaymentTokenUpdatedEvent.OutputTuple,
      PaymentTokenUpdatedEvent.OutputObject
    >;
    PaymentTokenUpdated: TypedContractEvent<
      PaymentTokenUpdatedEvent.InputTuple,
      PaymentTokenUpdatedEvent.OutputTuple,
      PaymentTokenUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SecurityIncident(address,string,uint256,uint256,string)": TypedContractEvent<
      SecurityIncidentEvent.InputTuple,
      SecurityIncidentEvent.OutputTuple,
      SecurityIncidentEvent.OutputObject
    >;
    SecurityIncident: TypedContractEvent<
      SecurityIncidentEvent.InputTuple,
      SecurityIncidentEvent.OutputTuple,
      SecurityIncidentEvent.OutputObject
    >;

    "SignerUpdated(address,address)": TypedContractEvent<
      SignerUpdatedEvent.InputTuple,
      SignerUpdatedEvent.OutputTuple,
      SignerUpdatedEvent.OutputObject
    >;
    SignerUpdated: TypedContractEvent<
      SignerUpdatedEvent.InputTuple,
      SignerUpdatedEvent.OutputTuple,
      SignerUpdatedEvent.OutputObject
    >;

    "TokensBurned(address,uint256,string,uint256)": TypedContractEvent<
      TokensBurnedEvent.InputTuple,
      TokensBurnedEvent.OutputTuple,
      TokensBurnedEvent.OutputObject
    >;
    TokensBurned: TypedContractEvent<
      TokensBurnedEvent.InputTuple,
      TokensBurnedEvent.OutputTuple,
      TokensBurnedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "UserDailyLimitUpdated(uint256)": TypedContractEvent<
      UserDailyLimitUpdatedEvent.InputTuple,
      UserDailyLimitUpdatedEvent.OutputTuple,
      UserDailyLimitUpdatedEvent.OutputObject
    >;
    UserDailyLimitUpdated: TypedContractEvent<
      UserDailyLimitUpdatedEvent.InputTuple,
      UserDailyLimitUpdatedEvent.OutputTuple,
      UserDailyLimitUpdatedEvent.OutputObject
    >;

    "VerifiedTokensBurned(address,uint256,uint256,bytes32)": TypedContractEvent<
      VerifiedTokensBurnedEvent.InputTuple,
      VerifiedTokensBurnedEvent.OutputTuple,
      VerifiedTokensBurnedEvent.OutputObject
    >;
    VerifiedTokensBurned: TypedContractEvent<
      VerifiedTokensBurnedEvent.InputTuple,
      VerifiedTokensBurnedEvent.OutputTuple,
      VerifiedTokensBurnedEvent.OutputObject
    >;
  };
}
